config/routes.rb
SampleApp::Application.routes.draw do
  
  resources :users 
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets
  resources :prices, only: [:create, :destroy, :edit, :update]
  

  root to: 'static_pages#home'

  match '/signup',   to: 'users#new'
  match '/signin',   to: 'sessions#new'
  match '/signout',  to: 'sessions#destroy', via: :delete

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/add_price', to: 'static_pages#add_price'

end

app/models/price.rb
class Price < ActiveRecord::Base
  attr_accessible :date, :price
  belongs_to :user
  validates :user_id, presence: true
  validates :date, presence: true
  validates :price, presence: true
  validates_uniqueness_of :date, :scope => [:user_id]
  validate :validate_date_in_past
  
  protected
  
  def validate_date_in_past
    # make sure date isn't in the future
    self.errors.add(:date, "cannot be in the future") if self.date.future?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password
  has_many :prices, dependent: :destroy
  

  before_save { |user| user.email = user.email.downcase }
  before_save :create_remember_token

  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  
  def send_password_reset
	  generate_token(:password_reset_token)
	  self.password_reset_sent_at = Time.zone.now
	  save!
	  UserMailer.password_reset(self).deliver
	end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end
  
  def create
	  user = User.find_by_email(params[:email])
	  user.send_password_reset if user
	  redirect_to root_url, :notice => "Email sent with password reset instructions."
	end
  def edit
	  @user = User.find_by_password_reset_token!(params[:id])
	end
	
  def update
  @user = User.find_by_password_reset_token!(params[:id])
  if @user.password_reset_sent_at < 2.hours.ago
    redirect_to new_password_reset_path, :alert => "Password &crarr; 
      reset has expired."
  elsif @user.update_attributes(params[:user])
    redirect_to root_url, :notice => "Password has been reset."
  else
    render :edit
  end
end
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  # respond_to :json, :html, :json, :js
  before_filter :signed_in_user
  before_filter :correct_user, only: :destroy
  

  def create
    @price = current_user.prices.build(params[:price])
    if @price.save
      flash[:success] = "price created!"
      redirect_to edit_price_path(current_user)
    else
      render 'static_pages/add_price'
    end
  end

  def destroy
    @price.destroy
    redirect_to root_path
  end
  
    
  def edit
    @datagrid   = Hash.new { |h,v| h[v] = {} }
    current_user.prices.each do |record|
      date = record.date
      @datagrid[date.year][date.month] = record
    end
	
  end

  def update
    @price=current_user.prices.find(params[:id])
    # if @price.update_attributes(params[:price])
      # flash[:success] = "Price updated"
	  # respond_with(@price, :location => price_url(@price))
      
    # else
      # render 'edit'
    # end
	respond_to do |format|
    if @price.update_attributes(params[:price])
      format.html { redirect_to(@price, :notice => 'Price was successfully updated.') }
      format.json { respond_with_bip(@price) }
    else
      format.html { render :action => "edit" }
      format.json { respond_with_bip(@price) }
    end
   end
  end

  private
  
  def signed_in_user
    redirect_to signin_url, notice: "Please sign in." unless signed_in?
  end
	
  def correct_user
    @price = current_user.prices.find_by_id(params[:id])
    redirect_to root_path if @price.nil?
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = "Invalid email/password combination"
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
   
  end

  def help
  end

  def about
  end

  def contact
  end
  
  def add_price
	if signed_in?
		 @price = current_user.prices.build
		 
	end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user,
                only: [:index, :edit, :update, :destroy, :following, :followers]
  before_filter :correct_user,   only: [:edit, :update, :show]
  before_filter :admin_user,     only: [:destroy, :index]

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
	@prices = @user.prices.paginate(page: params[:page])
	@datagrid   = Hash.new { |h,v| h[v] = {} }
    current_user.prices.each do |record|
      date = record.date
      @datagrid[date.year][date.month] = record
    end
   
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(params[:user])
      sign_in @user
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed"
    redirect_to users_path
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.followed_users.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private

    def correct_user
      @user = User.find(params[:id])
      redirect_to root_path unless current_user?(@user)
    end

    def admin_user
      redirect_to root_path unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = 'Class III Forward Price Contracts'
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def current_user?(user)
    user == current_user
  end

  def sign_out
    current_user = nil
    cookies.delete(:remember_token)
  end

  def store_location
    session[:return_to] = request.fullpath
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_path, notice: "Please sign in." 
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="future.aae.wisc.edu/">Understanding Dairy Markets</a>
    by Brian Gould
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "class III FPC", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "Help",    help_path %></li>
          <% if signed_in? %>
			<% if current_user.admin? %>
				 <li><%= link_to "Users", users_path %></li>
		    <% end %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/password_resets/edit.html.erb
<h1>Reset Password</h1>

<%= form_for @user, :url => password_reset_path(params[:id]) do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Update Password" %></div>
<% end %>

app/views/password_resets/new.html.erb
<h1>Reset Password</h1>

<%= form_tag password_resets_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %>
    <%= text_field_tag :email, params[:email] %>
  </div>
  <div class="actions"><%= submit_tag "Reset Password" %></div>
<% end %>

app/views/prices/edit.html.erb
<div class="mailbox_table">
<h3>Mailbox Prices </h3>

<%= link_to "Add Price", add_price_path %>
<table>
  <tr>
    <th>Month</th>
    <% (1..12).each do |m| -%>
    <th><%= Date::ABBR_MONTHNAMES[m] %></th>
    <% end -%>
  </tr>
<% @datagrid.keys.sort.each do |year| -%>
  <tr>
    <th><%= year %></th>
    <% (1..12).each do |month| -%>
      <% @price = @datagrid[year][month] -%>
      <td>
        <% if @price -%>
            <%= best_in_place @price, :price, :display_with => :number_to_currency %>       
        <% end -%>
      </td>
    <% end -%>
  </tr>
<% end -%>
</table>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_mailbox_form.html.erb
<%= form_for(@price) do |f| %>
  <%= render 'shared/error_messages', object: @price %>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date, discard_day:true %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price, step:"any" %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, size: 52 %>
</a>
<h1><%= current_user.name %></h1>
<span><%= link_to "View & Edit my Data", edit_price_path(current_user) %></span>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About</h1>
<p>
  Test test test test test test test test Test test test test test test test test Test test test test test test test test
  Test test test test test test test testTest test test test test test test testTest test test test test test test test
  Test test test test test test test testTest test test test test test test testTest test test test test test test test
  Test test test test test test test testTest test test test test test test testTest test test test test test test test
</p>

app/views/static_pages/contact.html.erb
<%= provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Test test test test test test test testTest test test test test test test testTest test test test test test test testTest test test test test test test test
  Test test test test test test test testTest test test test test test test testTest test test test test test test testTest test test test test test test test
  Test test test test test test test testTest test test test test test test testTest test test test test test test testTest test test test test test test test
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Test test test test test test test testTest test test test test test test testTest test test test test test test testTest test test test test test test testTest test test test test test test test
  Test test test test test test test testTest test test test test test test testTest test test test test test test testTest test test test test test test test
  Test test test test test test test testTest test test test test test test testTest test test test test test test testTest test test test test test test test
</p>

app/views/static_pages/home.html.erb
<% if signed_in? %>
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/stats' %>
      </section>
      <section>
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="span8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  <div class="center hero-unit">
    <h1>Welcome to the FPC Analyser </h1>
    <p>
      A Web-Based System for Evaluating Class III Forward Price Contracts      
    </p>

    <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
  </div>

  
<% end %>

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user.id),
             remote: true) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render 'unfollow' %>
    <% else %>
      <%= render 'follow' %>
    <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by_followed_id(@user),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete, confirm: "You sure?" %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: @user %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails" target="_blank">change</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: @user %>
      <%= f.label :name, "Account Name" %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
 </div>   
  </aside>
 <div class="mailbox_table">
    <% if @user.prices.any? %>
      <h3>Mailbox Prices </h3>
	  <%= link_to "Add Price", add_price_path %>
	  |
	  <%= link_to "Edit Prices", edit_price_path(current_user) %>
      <table>
  <tr>
    <th>Month</th>
    <% (1..12).each do |m| -%>
    <th><%= Date::ABBR_MONTHNAMES[m] %></th>
    <% end -%>
  </tr>
<% @datagrid.keys.sort.each do |year| -%>
  <tr>
    <th><%= year %></th>
    <% (1..12).each do |month| -%>
      <% @price = @datagrid[year][month] -%>
      <td>
        <% if @price -%>
            <%= number_to_currency(@price.price) %>       
        <% end -%>
      </td>
    <% end -%>
  </tr>
<% end -%>
</table>
      <%= will_paginate @prices %>
	  <% else %>
	  <%= link_to "Add Price", add_price_path %>
    <% end %>
	
  </div>

app/views/users/show_follow.html.erb
<%= provide(:title, @title) %>
<div class="row">
  <aside class="span4">
    <section>
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Microposts:</b> <%= @user.microposts.count %></span>
    </section>
    <section>
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="span8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>